# symmetry classes (48 x inverse) of wing.pool: 49 classes, 4048 algorithms
8 2B D B2 D' 2B' D B2 D'
8 2B D F' D' 2B' D F D'
8 2B D F2 D' 2B' D F2 D'
8 2B D' B D 2B' D' B' D
8 2B D' B2 D 2B' D' B2 D
8 2B D' F2 D 2B' D' F2 D
8 2B2 D B' D' 2B2 D B D'
8 2B2 D B2 D' 2B2 D B2 D'
8 2B2 D F' D' 2B2 D F D'
8 2B2 D F2 D' 2B2 D F2 D'
8 B 2D B' D2 B 2D' B' D2
8 B 2D B' U B 2D' B' U'
8 B 2D B' U2 B 2D' B' U2
8 B 2D' B' D B 2D B' D'
8 B 2D' B' U B 2D B' U'
8 B 2D' B' U2 B 2D B' U2
8 B 2D2 B' D B 2D2 B' D'
8 B 2D2 B' D' B 2D2 B' D
8 B 2D2 B' D2 B 2D2 B' D2
8 B 2D2 B' U B 2D2 B' U'
8 B 2D2 B' U' B 2D2 B' U
8 B 2D2 B' U2 B 2D2 B' U2
9 B 2D B D2 B' 2D' B D2 B2
9 B 2D B U B' 2D' B U' B2
9 B 2D2 B D B' 2D2 B D' B2
9 B 2D2 B U B' 2D2 B U' B2
9 B D 2B D' B D 2B' D' B2
9 B D 2F D' B D 2F' D' B2
9 B D 2F D' B2 D 2F' D' B
9 B D 2F' D' B D 2F D' B2
9 B D B 2D B' D' B 2D' B2
9 B D' B 2D B' D B 2D' B2
9 B D' B 2D2 B' D B 2D2 B2
9 B D2 B 2D B' D2 B 2D' B2
10 B 2D F' D' F 2D' F' D B' F
10 B 2D' F D' F' 2D F D B' F'
10 B D F 2D2 F' D' F 2D2 B' F'
10 B D L' 2D2 L D' L' 2D2 L B'
10 B D L' 2U2 L D' L' 2U2 L B'
10 B D' 2L' D L2 D' 2L D L2 B'
10 B F D B' 2D' B D' B' 2D F'
10 B F D B' 2U B D' B' 2U' F'
12 2B D R' B D' R 2B' R' D B' R D'
12 2B2 D R' B D' R 2B2 R' D B' R D'
12 B D F2 R' 2B R F2 R' 2B' R D' B'
12 B D' 2L' D B' L D' B 2L B' D L'
12 B D' 2L2 D B' L D' B 2L2 B' D L'
13 B D R' B 2D' B' R D' B R' 2D R B2
13 B D R' B 2U B' R D' B R' 2U' R B2
